---
# handlers file for change-sshd-port

- name: restart sshd
  become: yes
  service:
    name: sshd
    state: restarted

- name: restart firewalld
  become: yes
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
