---
# handlers file for change-sshd-port

- name: restart sshd
  become: yes
  service:
    name: sshd
    state: restarted

- name: restart firewall
  become: yes
  service:
    name: firewalld
    state: restarted
    
